// <auto-generated />
using System;
using BrandMicroservice.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrandMicroservice.src.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrandMicroservice.src.Models.DbModels.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("_id");

                    b.Property<string>("ControlName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("control_name");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FieldLabel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("field_label");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("field_type");

                    b.Property<string>("FormDescription")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("form_description");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("form_name");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("form_type");

                    b.Property<string>("HelpText")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("Multiple")
                        .HasColumnType("BOOL")
                        .HasColumnName("is_active");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.ToTable("forms", (string)null);
                });

            modelBuilder.Entity("BrandMicroservice.src.Models.DbModels.Make", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("company");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("date_updated");

                    b.Property<string>("MakeAbbreviation")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("make_abbreviation");

                    b.Property<string>("MakeCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("make_code");

                    b.Property<string>("MakeLogo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("make_logo");

                    b.Property<string>("MakeName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("make_name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("origin");

                    b.Property<int>("YearFounded")
                        .HasColumnType("integer")
                        .HasColumnName("year_founded");

                    b.HasKey("Id");

                    b.ToTable("makes", (string)null);
                });

            modelBuilder.Entity("BrandMicroservice.src.Models.DbModels.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("body_type");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("date_updated");

                    b.Property<Guid>("MakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("make_id");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("model_code");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("model_name");

                    b.Property<int>("YearFounded")
                        .HasColumnType("integer")
                        .HasColumnName("year_founded");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("BrandMicroservice.src.Models.DbModels.Model", b =>
                {
                    b.HasOne("BrandMicroservice.src.Models.DbModels.Make", "Makes")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makes");
                });

            modelBuilder.Entity("BrandMicroservice.src.Models.DbModels.Make", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
