name: brand-ms
services:
  brand-ms:
   container_name: brand-microservice
   build:
    context: .
   ports:
    - 5106:5106
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro      
    ports:
      - "443:443"
      - "80:80"