name: brand-ms
services:
  brand-ms:
   container_name: brand-microservice
   build:
    context: .
   ports:
    - 7000:7000
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5106:5106"