user root;

events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 443 ssl;
        server_name api.ibetech.online;

        ssl_certificate /etc/letsencrypt/live/ibetech.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/ibetech.online/privkey.pem;

        location / {
            proxy_pass http://brand-microservice:5106/;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

        server {
            listen 80;
            server_name api.ibetech.online;

            return 301 https://$host$request_uri;
    }
}